# Generated by Django 5.2.7 on 2025-10-21 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_negocio', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('whatsapp_negocio', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Barbearias',
                'db_table': 'barbearias',
            },
        ),
        migrations.CreateModel(
            name='Barbeiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='barbeiros/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('id_barbearia', models.ForeignKey(db_column='id_barbearia', on_delete=django.db.models.deletion.CASCADE, to='agenda.barbearias')),
            ],
            options={
                'verbose_name_plural': 'Barbeiros',
                'db_table': 'barbeiros',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao_minutos', models.IntegerField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_barbearia', models.ForeignKey(db_column='id_barbearia', on_delete=django.db.models.deletion.CASCADE, to='agenda.barbearias')),
            ],
            options={
                'verbose_name_plural': 'Serviços',
                'db_table': 'servicos',
            },
        ),
        migrations.CreateModel(
            name='HorariosDisponiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('id_barbeiro', models.ForeignKey(db_column='id_barbeiro', on_delete=django.db.models.deletion.CASCADE, to='agenda.barbeiros')),
            ],
            options={
                'verbose_name_plural': 'Horários Disponíveis',
                'db_table': 'horarios_disponiveis',
                'unique_together': {('id_barbeiro', 'data_hora')},
            },
        ),
        migrations.CreateModel(
            name='BarbeirosServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_barbeiro', models.ForeignKey(db_column='id_barbeiro', on_delete=django.db.models.deletion.CASCADE, to='agenda.barbeiros')),
                ('id_servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.CASCADE, to='agenda.servicos')),
            ],
            options={
                'verbose_name_plural': 'Relação Barbeiro-Serviço',
                'db_table': 'barbeiros_servicos',
                'unique_together': {('id_barbeiro', 'id_servico')},
            },
        ),
    ]
