# Generated by Django 5.2.7 on 2025-11-15 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='barbeiros/')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorariosDisponiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('disponivel', models.BooleanField(default=True)),
                ('id_barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='agenda.barbeiros')),
            ],
            options={
                'verbose_name_plural': 'Horários Disponíveis',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao_minutos', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='agenda.barbeiros')),
            ],
            options={
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone_cliente', models.CharField(max_length=15)),
                ('cpf_cliente', models.CharField(blank=True, max_length=14, null=True)),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agenda.horariosdisponiveis')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.servicos')),
            ],
        ),
    ]
