# Generated by Django 5.2.7 on 2025-10-25 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='id_barbearia',
        ),
        migrations.RemoveField(
            model_name='barbeiros',
            name='id_barbearia',
        ),
        migrations.AlterModelOptions(
            name='barbeiros',
            options={'verbose_name': 'Barbeiro', 'verbose_name_plural': 'Barbeiros'},
        ),
        migrations.AlterModelOptions(
            name='barbeirosservicos',
            options={'verbose_name': 'Serviço do Barbeiro', 'verbose_name_plural': 'Serviços dos Barbeiros'},
        ),
        migrations.AlterModelOptions(
            name='horariosdisponiveis',
            options={'ordering': ['id_barbeiro', 'data_hora'], 'verbose_name': 'Horário Disponível', 'verbose_name_plural': 'Horários Disponíveis'},
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='barbeirosservicos',
            name='id_barbeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.barbeiros', verbose_name='Barbeiro'),
        ),
        migrations.AlterField(
            model_name='barbeirosservicos',
            name='id_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.servicos', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='horariosdisponiveis',
            name='data_hora',
            field=models.DateTimeField(verbose_name='Data e Hora'),
        ),
        migrations.AlterField(
            model_name='horariosdisponiveis',
            name='id_barbeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.barbeiros', verbose_name='Barbeiro'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='duracao_minutos',
            field=models.IntegerField(default=39, help_text='Duração do serviço em minutos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicos',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterModelTable(
            name='barbeiros',
            table=None,
        ),
        migrations.AlterModelTable(
            name='barbeirosservicos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='horariosdisponiveis',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servicos',
            table=None,
        ),
        migrations.DeleteModel(
            name='Barbearias',
        ),
    ]
